
[sssd]
domains = advanced-media.co.jp
config_file_version = 2
services = nss, pam, autofs

[domain/advanced-media.co.jp]
ad_domain = advanced-media.co.jp
krb5_realm = ADVANCED-MEDIA.CO.JP
realmd_tags = manages-system joined-with-adcli 
cache_credentials = True
id_provider = ad
dyndns_update = false
krb5_store_password_if_offline = True
krb5_auth_timeout = 30
default_shell = /bin/bash
override_shell = /bin/bash
ldap_id_mapping = True
auto_private_groups = True
use_fully_qualified_names = False
fallback_homedir = /home/%u
access_provider = simple
ad_gpo_ignore_unreadable = True
#ad_enable_gc = False
#ldap_tls_reqcert = never
enumerate = True
#subdomains_provider = none
ldap_schema = ad
ldap_idmap_autorid_compat = True
ldap_idmap_default_domain     = advanced-media.co.jp
ldap_idmap_default_domain_sid = S-1-5-21-1241850295-1904294622-1478062314
ldap_idmap_range_min =    10000001
ldap_idmap_range_max =  2010000001
ldap_idmap_range_size = 200000
simple_allow_users = d-tanii, h-kawaguchi, h-kishi, k-ikeda, k-susuta, k-takemura, k-tejima, m-nakano, m-oka, n-koga, n-shinkai, r-oguro, r-suzuki, shiren, t-sasame, t-yamamoto, tanaka, y-kanemoto, y-sango, y-shigekuni

# ADプロバイダーの設定
autofs_provider = ad
ldap_autofs_search_base = ou=autofs,dc=advanced-media,dc=co,dc=jp
ldap_autofs_map_object_class = nisMap
ldap_autofs_map_name = nisMapName
ldap_autofs_entry_object_class = nisObject
ldap_autofs_entry_key = cn
ldap_autofs_entry_value = nisMapEntry
